### ISSUE TITLE
Another way to detect nginx config files

### ISSUE THREAD

**Issue by powerman** [joedeandev/prettier-plugin-nginx#10]
Using just `.nginx` and `.nginxconf` is not practical, we need some other ways to detect nginx configuration files.

Look, here is default nginx setup and it uses `.conf` and `_params` files:
```
$ docker run -i -t --rm nginx find /etc/nginx -type f 
/etc/nginx/scgi_params
/etc/nginx/uwsgi_params
/etc/nginx/nginx.conf
/etc/nginx/conf.d/default.conf
/etc/nginx/mime.types
/etc/nginx/fastcgi_params
```

And when I google for "nginx example sites-available" the first result use files without any extension (with paths like `/etc/nginx/sites-available/default` and `/etc/nginx/sites-available/DOMAIN.TLD`): https://www.digitalocean.com/community/tutorials/how-to-set-up-nginx-server-blocks-virtual-hosts-on-ubuntu-16-04#creating-the-first-server-block-file

From my experience these examples are very usual for any nginx setup. TBH I never seen in the wild examples of nginx config with all files having `.nginx` or `.nginxconf` extensions.

If your plugin sees full path then I propose to add `/nginx/` substring to default configuration (i.e. handle **all** files in `nginx/` dir as nginx config). Also it worth adding config option to let user add some others (using glob format, e.g. `*/my-proj/nginx-example-*/*`).

**Comment by jxddk** [comment]
`.nginx` and `.nginxconf` are the default values for this plugin because many other languages may use the `.conf` extension. As you noted in the issue description, there isn't any consistent convention for NGINX file extensions; I don't believe that there is a default glob pattern that will reliably match NGINX files without false positives.

If you'd like to apply this plugin to other paths that better fit your own projects, then you might find [the Prettier documentation for the `parser` override] helpful. For the example you gave, I believe that something like this would work:

```json
{
  "overrides": [
    {
      "files": "**/nginx/**",
      "options": { "parser": "nginx" }
    }
  ]
}
```

**Comment by C0ZEN** [comment]
@jxddk I followed this but got this error: [error] Couldn't resolve parser "nginx".
Any idea please?

**Comment by jxddk** [comment]
> [@jxddk](https://github.com/jxddk) I followed this but got this error: [error] Couldn't resolve parser "nginx". Any idea please?

That sounds like an environment configuration issue. I don't believe it's related to this repository, although for good measure, see if using [`prettier/plugin-xml`](https://github.com/prettier/plugin-xml) doesn't throw a similar error.
